name: LuccomInformatics
favicon: null
layout_spectrum: 0.38957627466879785
typography_spectrum: 0.22522387793287635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8188490977045149
  lightness: 0.8852006534580141
  saturation: 0.2527338929940015
  rhythmicContrast: 0.9892926542088389
purpose: []
